name: 'Bird Watcher'
description: 'Polls the repo for results of all local GitHub Actions'
inputs:
  token:
    description: 'GitHub token'
    required: true
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
